### ISSUE TITLE
Description in search results and detail pages

### ISSUE THREAD

**Issue by rsleggett** [Alchemy4Tridion/Alchemy4Tridion#10]
The description field from the a4t.xml is not shown in the webstore search results or on the detail page for our extension after upload

![capture](https://cloud.githubusercontent.com/assets/96642/8183671/983a4eb2-1431-11e5-9c14-b4176497e0c6.PNG)

I think this should not need to be entered twice

**Comment by alex-klock** [comment]
Currently the value in the description of the a4t.xml is not used to update the Web Store's description (vice versa, the Web Store populates the a4t.xml of the uploaded a4t package).

Will have it so that if the Web Store's Description is not yet set, the description in the xml will update it when you upload.
