### ISSUE TITLE
old config files remain

### ISSUE THREAD

**Issue by sponegg** [Alchemy4Tridion/Alchemy4Tridion#13]
I cannot get it to pick up my changes. No clue what the problem is, but it keeps on creating the old config files, old JS code, etc.

note from skype reply:

Rai: I was stuck in the same situation just now and I deleted everything under \Alchemy\Plugins_Packages\Temp - then I  could install newer versions

**Comment by alex-klock** [comment]
Added unloading of MSBuild project (this was causing caching issues with static files as MSBuild didn't pick up changes).

Added clearing of Temp folder, though not quite sure how this fixes as these were just used for .dll's since we couldn't delete them while they were locked.

We'll have to keep an eye out to see if this issue still exists after these fixes in 0.4.2.
