### ISSUE TITLE
password

### ISSUE THREAD

**Issue by sponegg** [Alchemy4Tridion/Alchemy4Tridion#15]
one of the users has a password that reads ""blah (with the quotes)

this breaks the config xml, this should be resolved with the password is stored as a hash

**Comment by alex-klock** [comment]
Adding encryption for the stored passwords which will secure the stored password as well as take care of things like quotes. Target for 0.4.2 release.

**Comment by alex-klock** [comment]
Password is now encrypted. However due to changes, impersonation is no longer needed by installing/uninstalling plugins.  The only piece at the moment using it is the Servicer plugin.

I removed the Impersonator from the Plugins lib and into the core lib (as this should not be accessible for plugin authors).  This is a breaking change for the Servicer plugin... which will now require the Core lib to be added as reference along with base Plugins.
