### ISSUE TITLE
Cannot download plugin

### ISSUE THREAD

**Issue by jhorsman** [Alchemy4Tridion/Alchemy4Tridion#29]
The download link on plugins on www.alchemywebstore.com does not work. Clicking the "Download Plugin" on the HelloWorld plugin links to http://www.alchemywebstore.com/api/plugins/557ef585e4de020df8a60383/download which shows error message "Authorization has been denied for this request".

This seem to be a problem for all plugins. Both when logged in or not. Installing the same plugins straight from the Alchemy tab in the CME is not a problem

**Comment by alex-klock** [comment]
Great catch Jan! Prior to the 0.4.2 release there actually wasn't any authentication on the download links... this was added in 0.4.2 however due to this being a SPA app, a direct link to the plugin download won't have the authentication token on it.

Updated the JS and the API controller to use an alternative "Request Download Token" style of authentication. You should now be able to download as normal. :) (note that only downloading from actual web store will work with this style... going to the download link directly will be unauthorized)
