### ISSUE TITLE
javascript libraries

### ISSUE THREAD

**Issue by sponegg** [Alchemy4Tridion/Alchemy4Tridion#6]
it's not possible to have separate js files in an external folder, these are all moved into the /scripts folder

**Comment by alex-klock** [comment]
Added change so that you can have a Library folder inside of your /Assets/Libs/ or /Static/Libs/ folder in your project.

ex:
/Static/Libs/AwesomeLib/<library files and sub folders here>

would be added to the package as:
/assets/libs/AwesomeLib/<library files and sub folders here>

You can then reference the root lib folder in a script tag using:

```
<script src="${LibsUrl}/AwesomeLib/awesome-lib.js"></script>
```

**Comment by alex-klock** [comment]
Reference on how to utilize JavaScript libs can be found at:
http://a4t-api.alchemywebstore.com/html/c1dded74-cd52-4494-bad8-e2b895bc9cf5.htm#JavaScriptLibraries
