### ISSUE TITLE
Popup after build not displayed on top 

### ISSUE THREAD

**Issue by Guzzter** [Alchemy4Tridion/Alchemy4Tridion#81]
Hi,

Could you make the WebStore popup (after a VS build) always visible on top?
Otherwise it looks like the build is hanging.

Other question: maybe you should only display the popup on a Release build. Then you can use Debug builds for local development more easily.

Best regards,
Guus

**Comment by alex-klock** [comment]
Issue with it randomly (or not so randomly) not coming to the front fixed (will be in 0.6.1 release) to now always be displayed at the top of all windows.

For the popup on release build only, there's actually already a way to configure it: https://github.com/Alchemy4Tridion/Alchemy4Tridion/issues/35 I'll add some documentation on Visual Studio Project Configuration soon to come so that these features are better known!
